### ISSUE TITLE
Competitions need a location

### ISSUE THREAD

**Issue by jfly** [jfly/ccm#22]
Ok, so competitions need a lot of things, but once we have their physical locations, we could do something cool like showing a map of all ongoing/soon/recent competitions on the home page, rather than a boring list.

**Comment by jbcm627** [comment]
This is now done just the google maps API (rather than a library on top of it).  I'm fairly happy with how it works right now, as of cc83faa.

It would be great to extract city/state/country data using on top of this too, as mentioned in #96, or to re-use this to ask competitors for locations like in #24.

I'm going to close this issue for now, and leave additional features for other issues.

**Comment by jfly** [comment]
I'm going to reopen this issue, as it looks like our map rendering isn't done reactively, so when someone else changes the location, the page doesn't update. I think the fix will be as easy as running `setCompetitionLocationMap()` inside of a `template.autorun()` here https://github.com/jfly/gjcomps/commit/cc83faa323d5a42c8084c40da531fcb4ebac439b#diff-1099b835a605090837b1e9f03adb11dcR266.
